### ISSUE TITLE
Patch & build Error: TX1 Kernel (Ubuntu 14.04 - 32bit)

### ISSUE THREAD

**Issue by santhoshrsk** [jetsonhacks/buildJetsonTX1Kernel#1]
Hi,
I am looking for building custom kernel to enable cp210x driver in my TX1 for ROS, Ros is working only in 32bit Ubuntu 14.04 .I have tried various methods to build and compile kernel, but nothing is working.
I followed the procedure given here in my TX1. while i am trying to patch and  build, i got these errors, i need some help to rectify these errors and enable cp210x driver in tx1.

"Generating include/generated/mach-types.h
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[1]: **\* [kernel/bounds.s] Error 1
make: **\* [prepare0] Error 2
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[1]: *** [kernel/bounds.s] Error 1
make: *** [prepare0] Error 2
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/data.o
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc.o
  CC      scripts/mod/empty.o
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[2]: *** [scripts/mod/empty.o] Error 1
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/dtc/flattree.o
make[1]:`include/generated/mach-types.h' is up to date.
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[1]: **\* [kernel/bounds.s] Error 1
make: **\* [prepare0] Error 2
make: **\* Waiting for unfinished jobs....
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
make: **\* [scripts] Error 2
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTCC  scripts/kallsyms
  CC      scripts/mod/empty.o
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[2]: **\* [scripts/mod/empty.o] Error 1
make[1]: **\* [scripts/mod] Error 2
make[1]: **\* Waiting for unfinished jobs....
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[1]: *** [kernel/bounds.s] Error 1
make: *** [prepare0] Error 2
make: *** Waiting for unfinished jobs....
make: *** [scripts] Error 2
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]:`include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[1]: **\* [kernel/bounds.s] Error 1
make: **\* [prepare0] Error 2
  IHEX    firmware/tigon/tg3.bin
  INSTALL /lib/firmware/tigon/tg3.bin
  IHEX    firmware/tigon/tg3_tso.bin
  INSTALL /lib/firmware/tigon/tg3_tso.bin
  IHEX    firmware/tigon/tg3_tso5.bin
  INSTALL /lib/firmware/tigon/tg3_tso5.bin"

and copy image gave this error

"ubuntu@tegra-ubuntu:~/buildJetsonTX1Kernel$ ./copyImage.sh 
cp: cannot stat ‘arch/arm64/boot/zImage’: No such file or directory
cp: cannot stat ‘arch/arm64/boot/Image’: No such file or directory"

**Comment by jetsonhacks** [comment]
The scripts in this repository are for 64-bit L4T 24.2 (Ubuntu 16.04). The kernel source is different from the 14.04 sources. AFAIK, the only way to compile the 64-bit kernel/32-bit user space is on a host using the NVIDIA prescribed toolchain. For additional information, please see:

http://jetsonhacks.com/2016/09/28/build-tx1-kernel-and-modules-nvidia-jetson-tx1/
