### ISSUE TITLE
Build Kernel Fail !

### ISSUE THREAD

**Issue by shuyu0815** [jetsonhacks/buildJetsonTX1Kernel#11]
My environment is
TX1
L4T 28.1.0
Board: t210ref
Ubuntu 16.04 LTS
Kernel Version: 4.4.38-tegra
( I haved Install SSD on it and followed by http://www.jetsonhacks.com/2017/01/28/install-samsung-ssd-on-nvidia-jetson-tx1/)

I want to install the tensorflow on TX1 ( https://github.com/jetsonhacks/installTensorFlowTX1 )

In the Preparation, I want to create the custom kernel must be used with swap enabled and 
I follow the step from the vedio released from : http://www.jetsonhacks.com/2017/08/07/build-kernel-ttyacm-module-nvidia-jetson-tx1/ 

I always get the same kernel version (4.4.38-tegra) after I reboot the TX1 (type the "uname -r ")
(I have found the free space change and got the DEPMOD 4.4.38-jetsonbot-v0.1)

Anyone can give me some suggestions ?
Thanks for help !

**Comment by jetsonhacks** [comment]
From the article:

Note: The copyImage.sh script copies the Image file to the /boot directory of the current device. If you are using an external device such as a SSD as your root directory and still using the eMMC to boot from, you will need to copy the Image file to the /boot directory of the eMMC, and modify /boot/extlinux/extlinux.conf accordingly.

This means that the Image file was built on the SSD. The Jetson boots from the eMMC. You will need to copy the Image file to the /boot directory of the eMMC, and modify /boot/extlinux/extlinux.conf on the eMMC for the changes to take effect.

**Comment by jetsonhacks** [comment]
Note that L4T 28.2 has swap enabled, consider upgrading. 
You should avoid building Tensor Flow yourself unless you are working on TensorFlow source code.
You can get pre-built .whl files from: 
https://github.com/peterlee0127/tensorflow-nvJetson
Upgrade to L4T 28.2 (JetPack 3.2) and use these instructions from Jason at NVIDIA:
https://github.com/JasonAtNvidia/JetsonTFBuild

**Comment by shuyu0815** [comment]
Sorry, I'm the freshman on TX1 !  

I can't catch what your mean of copying the Image file to the /boot directory of the eMMC !

I have change the DEFAULT from satassd to emmc  (/boot/extlinux/extlinux.conf) 
and do the following steps !
1. reboot 
2. follow the step from the vedio : http://www.jetsonhacks.com/2017/08/07/build-kernel-ttyacm-module-nvidia-jetson-tx1/
3. reboot with the DEFAULT is emmc  (/boot/extlinux/extlinux.conf) 
but also get the same kernel version (4.4.38-tegra) 

the file of /boot/extlinux/extlinux.conf:
"
TIMEOUT 30
DEFAULT emmc

MENU TITLE p2371-2180 eMMC boot options

LABEL satassd
      MENU LABEL primary SATA SSD
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/sda rw rootwait

LABEL emmc
      MENU LABEL Internal eMMC
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait
"

Is any probability it always reboot with SSD boot and how to check that ?

the second question is that what your mean of "You should avoid building Tensor Flow yourself unless you are working on TensorFlow source code."
you mean if I only want to deploy inference on TX1, I shouldn't follow the vedio: https://github.com/jetsonhacks/installTensorFlowTX1 ? 

sorry I'm freshman all of them !
Thank you very much !

**Comment by jetsonhacks** [comment]
In the SSD case, the Jetson boots from the eMMC. That is where you need to have the newly created Image file, in the /boot directory on the eMMC. The eMMC will appear as an SD card when using the SSD as the root directory. 

Your extlinux.conf above sets the root directory. The sequence is:

- Jetson Boots from the Image file located on the internal eMMC
- It reads the extlinux.conf file from the eMMC.
- It reads the root argument and then sets the root directory to point to that device
- Switches over to the root directory on the selected device then continues

In your case, you built the new Image file on the SSD. The copyImage script copied it to the /boot directory on the root directory, which is on the SSD. When you reboot, the Image file on the eMMC is still the same old one, so nothing changes.

The TensorFlow build scripts builds TensorFlow from source. The links provided above provided precompiled binaries for the Jetson (so you can just run TensorFlow, and not have to build it from source), along with updated instructions for building the Jetson from source if so desired.

**Comment by shuyu0815** [comment]
Thank you very much !
I copied the Image to the /boot directory on the eMMC successfully and create the custom kernel must be used with swap enabled ! 

You means if I only want to run tensorflow on TX1 and I can only install tensorflow from pre-build wheel file (by  https://github.com/jetsonhacks/installTensorFlowJetsonTX) 
not from source (by https://github.com/jetsonhacks/installTensorFlowTX1)? 

Thank again for your reply !

**Comment by jetsonhacks** [comment]
TensorFlow is an application. "Building", also referred to as compiling, takes the human readable source code and converts it to machine executable form. The machine executable form is referred to as binary, or pre-built. The binary is then installed on the machine.
There are pre-built binaries available for TensorFlow as noted above. If your intention is to run TensorFlow the application, you should install the binaries. If your intention is to modify the TensorFlow application source code, then you would go through the build process.
From your description, you should be installing the binaries.
