### ISSUE TITLE
Updating to 24.2.1

### ISSUE THREAD

**Issue by Ashram56** [jetsonhacks/buildJetsonTX1Kernel#2]
It looks like these steps do not work with latest Jetpack 24.2.1, even when replacing manually the source code.

Has anyone update this kernel build procedure for the latest Jetpack ?

**Comment by jetsonhacks** [comment]
Please write the issue that you are having. "steps do not work" doesn't mean anything.

**Comment by Ashram56** [comment]
I apologize for the lack of details, I must admit in retrospect this was really sparse information.

Anyway, I figured out what I was doing wrong on my setup, the issue is resolved.

Essentially, I downloaded the source from this link:
https://developer.nvidia.com/embedded/dlc/l4t-sources-24-2-1

From there I extracted manually the kernel source, modified the scripts to reflect the correct path (and not download the original file - which I assume is kernel from 24.2, although I did not perform a file compare)

Regards

**Comment by jetsonhacks** [comment]
Glad to hear you got it working!
