### ISSUE TITLE
rplidar

### ISSUE THREAD

**Issue by aysegulucar2016** [jetsonhacks/buildJetsonTX1Kernel#4]
To introduce  Rplidar A1 version to TX1, 

Should I install both 

the sh files in jetsonhacks/buildJetsonTX1Kernel

and
the sh files in https://github.com/jetsonhacks/TX1FTDIModule ?

Could you please say?  Many thanks

**Comment by jetsonhacks** [comment]
Depends on what you're trying to do. If you're trying to build a kernel or modules, buildJetsonTX1Kernel is useful. I do not know why you would use the FTDI module, my understanding is that it runs off of the CP2102 chipset. You need to build a module for the CP2102.
