### ISSUE TITLE
We obtained "freeing unused kernel memory"

### ISSUE THREAD

**Issue by aysegulucar2016** [jetsonhacks/buildJetsonTX1Kernel#5]
We obtained "freeing unused kernel memory"  and "freeng alternative memory" after reboot and ./copyImage.sh.

When we run "uname -r" , we cant see jetsonboot also and the date is old, not this today.

We are running Jetson TX1 from an external sata disk (500gb).

How can we solve the problem. Could you please say?

**Comment by jetsonhacks** [comment]
>> We obtained "freeing unused kernel memory" and "freeng alternative memory" after reboot and ./copyImage.sh.

This message is from the old kernel. I do not know what that issue may be.

If you run "uname -r" and see the old kernel, you have not replaced the old kernel with the new one. The images must be copied to the boot directory of the device that you are booting from. The copyImage.sh copies the boot images that were built in the kernel source directory to the current roots' directory boot directory. I do not know the specifics of your case, but could it be that you are booting off of the eMMC and then setting the root directory to point to the SSD?

**Comment by aysegulucar2016** [comment]
Many thanks for fast answer. we copied image and zimage and controlled their dates. The dates show today. We previously setted extlinux.conf File as

LABEL satahdd
MENU LABEL primary SATA HDD
LINUX /boot/Image
INITRD /boot/initrd
----
LABEL emmc
MENU LABEL Internal eMMC
LINUX /boot/Image
INITRD /boot/initrd

**Comment by jetsonhacks** [comment]
Is this on the eMMC or the SSD? What is the root directory setting?

**Comment by aysegulucar2016** [comment]
We exactly carried out ones at your link
http://www.jetsonhacks.com/2017/01/28/install-samsung-ssd-on-nvidia-jetson-tx1/  .

Our root directory is
/media/ubuntu/JetsonHDD-500

**Comment by aysegulucar2016** [comment]
![4](https://cloud.githubusercontent.com/assets/16757934/24619975/a3e22e6e-18a4-11e7-9167-342868244ad8.png)

**Comment by aysegulucar2016** [comment]
![3](https://cloud.githubusercontent.com/assets/16757934/24619987/afc4205c-18a4-11e7-93a7-4fb5c8ec7e4d.png)

**Comment by aysegulucar2016** [comment]
![2](https://cloud.githubusercontent.com/assets/16757934/24620003/c57d24fc-18a4-11e7-96b8-821149c1f974.png)

**Comment by jetsonhacks** [comment]
Right, so you've identified the problem. You are booting from the eMMC. You built a kernel on the SSD. The copyImage script copies the built kernel on the root directory to the root directory boot area. However, since you are booting from another device entirely, you must copy the kernel image to the actual device that is booting.  In your case, you must copy the zImage and Image files located on the SSD /usr/src/kernel/arch/arm64/boot directory to the eMMC /boot directory.

**Comment by aysegulucar2016** [comment]
Many thanks for all detalied answers. Everything is ok.

**Comment by jetsonhacks** [comment]
Glad you got it running!
