### ISSUE TITLE
changing the path to the kernel

### ISSUE THREAD

**Issue by nlyubova** [jetsonhacks/buildJetsonTX1Kernel#6]
Hello, 
thank you for posting your scripts here!
I wonder if it is possible to change the path to the kernel (on the disk) when doing makeKernel1.sh ? I get this error because it assumes the kernel in /usr/src/ that is not the case: 
firmware/audience/es755/audience-es755-fw.bin.gen.S:5: Error: file not found: /usr/src/kernel/firmware/audience/es755/audience-es755-fw.bin

I would really appreciate your help!

**Comment by jetsonhacks** [comment]
Where is the file /usr/src/kernel/firmware/audience/es755/audience-es755-fw.bin
What version of L4T are you running?
If you are using the scripts in this repository, the scripts download the source and unpack it into /usr/src/kernel 
Therefore if you're missing the audience firmware, it's because it's missing from the source for some reason.

**Comment by nlyubova** [comment]
right, according to your script, the kernel should be downloaded to /usr/src/kernel and your script works perfectly in this case.

However, in the case of not having any space on the disk and downloading the kernel to an external drive, Is it still possible to use your script by changing the path to the kernel? can we provide a path to the kernel in makeKernel1.sh?

**Comment by jetsonhacks** [comment]
If I understand your issue correctly, you will need to change all of the scripts in the scripts folder from pointing to /usr/src to your new kernel build directory. It is not sufficient to change only  makeKernel1.sh The kernel still needs to be patched with tegraClocks in the top level patchAndBuildKernel.sh 

The basic summary is to change /usr/src in all of the script files in the repository to your new build directory.

**Comment by nlyubova** [comment]
right, I have passed all of them up to makeKernel1.sh (on make) and I'm stuck here.

**Comment by jetsonhacks** [comment]
Where is the file: audience-es755-fw.bin
on your system?

**Comment by nlyubova** [comment]
on the external driver, as it is a part of kernel, right?

**Comment by jetsonhacks** [comment]
The file is located in the source tree of the kernel. It is located where you unpacked the kernel source. The scripts in this repository unpacked the source for the kernel in /usr/src. Therefore it looks in /usr/src/kernel/firmware/audience/es755/audience-es755-fw.bin
The location that the source gets downloaded is determined in the file: ./scripts/installKernelSources.sh
in the line: 
cd /usr/src
If you are building on an external drive, then you must change that line to point to your external drive.
What are the contents of your modified files:
./scripts/installKernelSources.h
./scripts/makeKernel.sh
./scripts/makeKernel1.sh
./scripts/patchKernel.sh
Are you running the buildJetsonTX1Kernel repository from the external drive?

**Comment by nlyubova** [comment]
Everything went well until ./scripts/makeKernel1.sh
However, modifying the path in ./scripts/makeKernel1.sh does not help.
Thus, I go to the "kernel" folder and do "make" there and then I get an error  firmware/audience/es755/audience-es755-fw.bin.gen.S:5: Error: file not found: /usr/src/kernel/firmware/audience/es755/audience-es755-fw.bin

I wonder if you could know where should we modify the path in the kernel/Makefile file?

**Comment by jetsonhacks** [comment]
I'll keep asking:
What are the contents of the files that you modified to set your kernel source tree:
./scripts/installKernelSources.h
./scripts/makeKernel.sh
./scripts/makeKernel1.sh
./scripts/patchKernel.sh
Are you running the buildJetsonTX1Kernel repository from the external drive?
What is the path location to the file kernel/firmware/audience/es755/audience-es755-fw.bin

Once you answer those questions I will be able to help.

Please consider building the kernel on your PC: https://developer.ridgerun.com/wiki/index.php?title=Compiling_Tegra_X1_source_code

**Comment by nlyubova** [comment]
I am taking this kernel http://developer.nvidia.com/embedded/dlc/l4t-sources-24-2-1

**Comment by nlyubova** [comment]
it seams that it is compiled now. thank you for your package!

**Comment by jetsonhacks** [comment]
Glad to hear you got it to work!
